name: rainforest_biz_project
description: ''
version: 0.0.1
author: shashank@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: rainforestbizproject
  parentArtefactID: shashankprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-03-06 09:33:14'
pipelines:
  pipelines/enrich_accounts:
    name: enrich_accounts
    description: ''
    author: shashank@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-03-06 09:33:14'
    datasets:
      inputs:
      - datasets/food_dataset
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/food_dataset:
    name: food_dataset
    description: ''
    author: shashank@prophecy.io
    createdAt: '2024-03-06 11:00:08'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 10061
        datasetType: File
        description: ''
        author: shashank@prophecy.io
        createdAt: '2024-03-06 11:00:09'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-03-06 09:33:14'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.4
    isDefault: true
    author: null
    createdAt: '2024-03-06 09:21:14'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.3
    isDefault: true
    author: null
    createdAt: '2024-03-06 09:21:14'
  '12656':
    projectUID: 12656
    projectName: ProphecyStreamingPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12656.git&subPath=
    version: 0.0.2
    isDefault: false
    author: null
    createdAt: '2024-03-06 09:21:14'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
